[package]
name = "ecosim"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
rand09 = { package = "rand", version = "0.9.2" }
num_cpus = "1.16"
getrandom = { version = "0.3", features = ["wasm_js"] }
